name: Linting, Scanning, and Integration Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install mariadb
        run: apt-get install mariadb
      - name: Configure mariadb for Tests
        continue-on-error: true
        run: |
        systemctl start mariadb
        echo -e "\n\npassword\npassword\n\n\nn\n\n " | mysql_secure_installation 2>/dev/null
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
        python -m pip install --upgrade pip
        pip install mysql flake8 bandit
      - name: Lint with flake8
        run: flake8 xtldp/dal/mariadb/
        continue-on-error: true
      - name: Code Scan with Bandit
        run: bandit xtldp/dal/mariadb/
        continue-on-error: true
      - name: Running Auth Testing
        run: python3 -m unittests tests/mariadb/test_auth.py
        continue-on-error: true
      - name: Running Database Testing
        run: python3 -m unittests tests/mariadb/test_database.py
        continue-on-error: true
      - name: Running Table Testing
        run: python3 -m unittests tests/mariadb/test_table.py
        continue-on-error: true
      - name: Running Row Testing
        run: python3 -m unittests tests/mariadb/test_row.py
        continue-on-error: true