name: Linting, Scanning, and Integration Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install mariadb
        run: |
          sudo apt install mariadb-server mariadb-client -y
      - name: Configure mariadb for Tests
        continue-on-error: true
        run: |
          sudo systemctl start mariadb
          sed -e 's/\s*\([\+0-9a-zA-Z]*\).*/\1/' << EOF | mysql_secure_installation
  # current root password (emtpy after installation)
y # Set root password?
password # new root password
password # new root password
y # Remove anonymous users?
y # Disallow root login remotely?
y # Remove test database and access to it?
y # Reload privilege tables now?
EOF
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql flake8 bandit
      - name: Lint with flake8
        run: flake8 xtldp/dal/mariadb/
        continue-on-error: true
      - name: Code Scan with Bandit
        run: bandit xtldp/dal/mariadb/
        continue-on-error: true
      - name: Running Auth Testing
        run: python3 -m unittests tests/mariadb/test_auth.py
        continue-on-error: true
      - name: Running Database Testing
        run: python3 -m unittests tests/mariadb/test_database.py
        continue-on-error: true
      - name: Running Table Testing
        run: python3 -m unittests tests/mariadb/test_table.py
        continue-on-error: true
      - name: Running Row Testing
        run: python3 -m unittests tests/mariadb/test_row.py
        continue-on-error: true