name: Linting, Scanning, and Integration Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb:latest
        ports:
          - 3306
        env:
          MYSQL_USER: user
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: password
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Verify MariaDB connection
        env:
          PORT: ${{ job.services.mariadb.ports[3306] }}
        run: |
          while ! mysqladmin ping -h"127.0.0.1" -P"$PORT" --silent; do
            sleep 1
          done          

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mysql flake8 bandit
      - name: Lint with flake8
        run: flake8 xtldp/dal/mariadb/
        continue-on-error: true
      - name: Code Scan with Bandit
        run: bandit xtldp/dal/mariadb/
        continue-on-error: true
      - name: Running Auth Testing
        run: python3 -m unittest tests/mariadb/test_auth.py
        continue-on-error: true
      - name: Running Database Testing
        run: python3 -m unittest tests/mariadb/test_database.py
        continue-on-error: true
      - name: Running Table Testing
        run: python3 -m unittest tests/mariadb/test_table.py
        continue-on-error: true
      - name: Running Row Testing
        run: python3 -m unittest tests/mariadb/test_row.py
        continue-on-error: true